### ISSUE TITLE
LIMIT_HITS_PER_VHOST

### ISSUE THREAD

**Issue by Bagerter** [NetAngels/ddosguard#2]
LIMIT_HITS_PER_VHOST
блокирует всех, не только ботов
Как пофиксить?

**Comment by antony66** [comment]
Это фича, специально сделанная для массового хостинга как "второй эшелон" защиты. Если у вас на сервере много сайтов и вы знаете что их типичная посещаемость не превышает `N`, то `LIMIT_HITS_PER_VHOST` в конфиге нужно установить, например, в значение `N*5`, либо какое вы сами сочтете нужным. Тогда если у каких-то отдельных сайтов возникнет внезапный всплеск посещаемости, `LIMIT_HITS_PER_VHOST` его заблокирует. Если этот функционал не требуется, просто установите значение `LIMIT_HITS_PER_VHOST` заведомо очень большим.

**Comment by Bagerter** [comment]
Смысл в том, что он сразу блокирует всех при старте атаки, ошибок по limit_hits_per_ip нету
